package type_erasure;

import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        // This whole thing
        List<String> list = new ArrayList<>();
        list.add("foo");
        String x = list.getFirst();

        // Becomes this after compilation, because the compiler removes everything and uses casts for the generated bytecode,
        // this is called "type erasure"
        List list2 = new ArrayList();
        list2.add("foo");
        String x2 = (String) list.getFirst();
    }
}
